# Generated by Django 2.0.7 on 2018-07-30 17:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('bio', models.TextField(validators=[accounts.models.min_length])),
                ('avatar', models.BooleanField()),
            ],
        ),
    ]
