# Generated by Django 2.0.7 on 2018-08-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180804_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='USERNAME_FIELD',
            new_name='first_name',
        ),
    ]
